version: '3'

services:
  postgres_data:
    image: busybox
    volumes:
        - /var/lib/postgresql/data
    container_name: postgres-datastore

  db:
    image: postgres
    environment:
      POSTGRES_USER: python
      POSTGRES_PASSWORD: triple4649
    ports:
      - "5432:5432"
    container_name: postgres
    volumes:
      - postgres-datastore

  web:
    build: .
    ports:
     - "5000:5000"
    volumes:
     - .:/myapp
    env_file: .env
    depends_on:
     - db
    container_name: web-container
