"""empty message

Revision ID: 490d6ca57fb0
Revises: 
Create Date: 2020-02-18 22:57:18.757064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '490d6ca57fb0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('recieve_user_image_url', sa.String(length=1024), nullable=True))
    op.add_column('questions', sa.Column('send_user_image_url', sa.String(length=1024), nullable=True))
    op.drop_column('questions', 'profile_image_url')
    op.drop_column('questions', 'answer_image_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('answer_image_url', sa.VARCHAR(length=1024), nullable=True))
    op.add_column('questions', sa.Column('profile_image_url', sa.VARCHAR(length=1024), nullable=True))
    op.drop_column('questions', 'send_user_image_url')
    op.drop_column('questions', 'recieve_user_image_url')
    # ### end Alembic commands ###
